# Generated by Django 3.1.14 on 2022-03-01 07:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_fsm_log", "0006_allow_non_numeric_ids"),
        ("django_fsm_log", "0004_auto_20190131_0341"),
    ]

    operations = []
